[versions]
agp = "8.13.0"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "35"
androidx-activityCompose = "1.11.0"
coroutines = "1.10.2"
compose-navigation = "2.9.0"
coil-core = "3.3.0"
foundationAndroid = "1.9.3"
composeIcons = "1.1.1"
jetbrainsKotlinJvm = "2.2.20"
ktor = "3.3.1"
koin = "4.1.1"
buildKonfig = "0.17.1"
viewModel = "2.9.4"
kermit = "2.0.8"
paging = "3.3.0-alpha02-0.5.1"
media3 = "1.8.0"
kotlin = "2.2.20"
kotlin-serialization = "1.9.0"
kotlin-datetime = "0.7.1-0.6.x-compat"
kotlin-compose-plugin = "1.9.0"
cupertino = "2.3.1" #0.1.0-alpha04
firebase = "2.1.0"
composeResources = "1.9.0"

[libraries]
androidx-foundation-android = { group = "androidx.compose.foundation", name = "foundation-android", version.ref = "foundationAndroid" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }

kotlin-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlin-datetime" }
kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "viewModel" }
compose-navigation = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "compose-navigation" }


serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin-serialization" }

coil-core = { group = "io.coil-kt.coil3", name = "coil", version.ref = "coil-core" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil-core" }
coil-compose-core = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coil-core" }
coil-ktor = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil-core" }
coil-client-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil-core" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }


koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-viewModel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }

composeIcons-fontAwesome = { module = "br.com.devsrsouza.compose.icons:font-awesome", version.ref = "composeIcons" }

kermit = { group = "co.touchlab", name = "kermit", version.ref = "kermit" }

paging = { group = "app.cash.paging", name = "paging-compose-common", version.ref = "paging" }

media3-core = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
media3-dash = { group = "androidx.media3", name = "media3-exoplayer-dash", version.ref = "media3" }
media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
media3-common = { group = "androidx.media3", name = "media3-common-ktx", version.ref = "media3" }

cupertino = { group = "io.github.schott12521", name = "cupertino", version.ref = "cupertino" }
cupertino-adaptive = { group = "io.github.schott12521", name = "cupertino-adaptive", version.ref = "cupertino" }
cupertino-native = { group = "io.github.schott12521", name = "cupertino-native", version.ref = "cupertino" }
cupertino-icons-extended = { group = "io.github.schott12521", name = "cupertino-icons-extended", version.ref = "cupertino" }

firebase-auth = { group = "dev.gitlive", name = "firebase-auth", version.ref = "firebase" }
firebase-firestore = { group = "dev.gitlive", name = "firebase-firestore", version.ref = "firebase" }
firebase-storage = { group = "dev.gitlive", name = "firebase-storage", version.ref = "firebase" }

compose-resources = { group = "org.jetbrains.compose.components", name = "components-resources", version.ref = "composeResources" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = "2.2.20" }
buildKonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildKonfig" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "kotlin-compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

[bundles]
media3 = ["media3-core", "media3-common", "media3-ui", "media3-dash"]
cupertino = ["cupertino", "cupertino-adaptive", "cupertino-native", "cupertino-icons-extended"]
firebase = ["firebase-auth", "firebase-firestore", "firebase-storage"]